name: Setup
description: Setup
inputs:
  ghcr-pat:
    description: The PAT to login to GitHub Container registry
    required: false
  aws-directory:
    description: The directory to store AWS credentials
    required: false
    default: ~/.aws
  aws-region:
    description: The AWS region
    required: false
  aws-account-id:
    description: The AWS account ID
    required: false
  aws-role-name:
    description: The AWS role name
    required: true
    default: GitHub
  ssh-directory:
    description: The directory to store SSH
    required: false
    default: ~/.ssh
  ssh-private-key:
    description: The SSH private key
    required: false
outputs:
  git-hash-short:
    description: The Git short hash
    value: ${{ steps.git-hash.outputs.hash }}
runs:
  using: composite
  steps:
    - name: Login to GitHub Container registry
      if: inputs.ghcr-pat != ''
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-pat }}
    - name: Configure AWS credentials
      if: inputs.aws-region != '' && inputs.aws-account-id != '' && inputs.aws-role-name != ''
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.aws-role-name }}
    - name: Store AWS credentials
      if: inputs.aws-region != '' && inputs.aws-account-id != '' && inputs.aws-role-name != ''
      shell: sh
      run: |
        mkdir -p ${{ inputs.aws-directory }}
        echo "[default]" > ${{ inputs.aws-directory }}/credentials
        echo "aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }}" >> ${{ inputs.aws-directory }}/credentials
        echo "aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}" >> ${{ inputs.aws-directory }}/credentials
        echo "aws_session_token = ${{ env.AWS_SESSION_TOKEN }}" >> ${{ inputs.aws-directory }}/credentials
    - name: Login to AWS ECR
      if: inputs.aws-region != '' && inputs.aws-account-id != '' && inputs.aws-role-name != ''
      uses: aws-actions/amazon-ecr-login@v1
    - name: Setup SSH
      if: inputs.ssh-private-key != ''
      shell: sh
      run: |
        mkdir -p ${{ inputs.ssh-directory }}
        echo "${{ inputs.ssh-private-key }}" > ${{ inputs.ssh-directory }}/id_rsa
        chmod 600 ${{ inputs.ssh-directory }}/id_rsa
    - name: Set Git hash short
      id: git-hash
      shell: sh
      run: echo "::set-output name=hash::$(echo ${{ github.sha }} | cut -c 1-10)"
